// Content collections for CLOELIA.AI. Two kinds:
//   editorial  (src/content/<collection>/*.yaml): dimensions, places, records, developments,
//              populations, sources, questions, corrections. Authored by hand, in the source's terms.
//   bridged    (src/content/bridge/<collection>/*.json): investigations, measures, findings, charts,
//              datasets. Generated by scripts/bridge.mjs from the lab's publish/ folders (artifact
//              contract v1) and committed; never edited by hand. No number on the site comes from
//              anywhere else.
// Every relationship is by slug; scripts/validate.mjs fails the build on a dangling reference and
// on any breach of the Neutrality and Evidence Standard's required fields.
import { defineCollection } from 'astro:content';
import { glob } from 'astro/loaders';
import { z } from 'astro/zod';

const yaml = (name: string) => glob({ pattern: '**/*.yaml', base: `./src/content/${name}` });
const json = (name: string) => glob({ pattern: '**/*.json', base: `./src/content/bridge/${name}` });

const slug = z.string().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/, 'lower-case slug');
const isoDate = z.string().regex(/^\d{4}(-\d{2}(-\d{2})?)?$/, 'a year, or an ISO date');
const EM_DASH = String.fromCharCode(0x2014);
const noEmDash = (s: string) => !s.includes(EM_DASH);
const text = z.string().min(1).refine(noEmDash, 'no em dashes');

export const GRADES = ['measured', 'documented', 'inferred', 'contested', 'insufficient'] as const;
export const KINDS = ['measure-begins', 'law', 'institution', 'practice', 'technology', 'event', 'definition-change'] as const;

const dimensions = defineCollection({
  loader: yaml('dimensions'),
  schema: z.object({
    name: text,
    definition: text,
    not_covered: z.array(text).default([]),
    candidate_measures: z.array(z.object({ name: text, source: text })).default([]),
    lens: z.array(z.enum(['economic', 'housing', 'education', 'social', 'technological'])).default([]),
  }).strict(),
});

const places = defineCollection({
  loader: yaml('places'),
  schema: z.object({
    name: text,
    level: z.enum(['country', 'state', 'county', 'city']),
    boundary_notes: z.array(z.object({ year: z.number().int(), note: text })).default([]),
    parent: slug.optional(),
  }).strict(),
});

const populations = defineCollection({
  loader: yaml('populations'),
  schema: z.object({ name: text, definition: text, source_terms: text.optional() }).strict(),
});

const sources = defineCollection({
  loader: yaml('sources'),
  schema: z.object({
    type: z.enum(['primary', 'secondary']),
    citation: text,
    where_found: text,
    retrieved: isoDate,
    url: z.url().optional(),
    passage: z.string().refine(noEmDash, 'no em dashes').default(''),
  }).strict().refine((s) => s.type === 'secondary' || s.passage.trim().length > 0, {
    message: 'a primary source needs the passage used',
  }),
});

const developments = defineCollection({
  loader: yaml('developments'),
  schema: z.object({
    record: z.object({ dimension: slug, place: slug }),
    date: isoDate,
    kind: z.enum(KINDS),
    text,
    applies_to: z.array(slug).min(1, 'every development names the population it applied to'),
    sources: z.array(slug).min(1, 'every development cites at least one source'),
  }).strict(),
});

const questions = defineCollection({
  loader: yaml('questions'),
  schema: z.object({
    record: z.object({ dimension: slug, place: slug }),
    text,
    status: z.enum(['open', 'in-investigation', 'answered', 'insufficient-evidence']),
    investigation: z.string().optional(),
    asked: isoDate,
    note: text.optional(),
  }).strict(),
});

const corrections = defineCollection({
  loader: yaml('corrections'),
  schema: z.object({
    date: isoDate,
    target: text,
    what: text,
    why: text,
  }).strict(),
});

const records = defineCollection({
  loader: yaml('records'),
  schema: z.object({
    dimension: slug,
    place: slug,
    period: z.object({ from: z.number().int(), to: z.number().int() }),
    covers: text,
    not_covered: z.array(text).default([]),
    measures: z.array(slug).min(1, 'a Record shows at least one measure'),
    headline_finding: z.string().min(1, 'the scan layer needs the finding that states the major measured change'),
    status: z.enum(['draft', 'staging', 'published']),
    chronicle_note: text.optional(),
  }).strict(),
});

// ---- bridged collections (artifact contract v1) ----
const investigations = defineCollection({
  loader: json('investigations'),
  schema: z.object({
    contract_version: z.literal('1.0.0'),
    id: z.string(),
    number: z.number().int(),
    question: text,
    hypothesis: text,
    level: z.number().int().min(1).max(6),
    new_skills: z.array(text).min(1).max(2),
    status: z.enum(['verified', 'published']),
    dates: z.object({ opened: isoDate, verified: isoDate }),
    notebook: text,
    verification: z.object({ run_all_sequential: z.literal(true), zero_errors: z.literal(true), raw_hashes_match: z.literal(true), checked_on: isoDate }),
    raw_files: z.array(z.object({ path: text, sha256: z.string().regex(/^[0-9a-f]{64}$/) })).min(1),
    assistance: text,
    record: z.object({ dimension: slug, place: slug }),
    lab_commit: z.string().regex(/^[0-9a-f]{7,40}$/),
    bridged_on: isoDate,
  }).strict(),
});

const measures = defineCollection({
  loader: json('measures'),
  schema: z.object({
    slug,
    investigation: z.string(),
    name: text,
    definition: text,
    unit: text,
    population: text,
    dataset: text,
    cell: z.number().int(),
    years: z.object({ from: z.number().int(), to: z.number().int() }),
    gaps: z.array(z.number().int()),
    definition_changes: z.array(z.object({ year: z.number().int(), note: text })),
    geographies: z.array(z.string()).min(1),
    rows: z.array(z.object({
      year: z.number().int(),
      geography: z.string(),
      population: z.string(),
      value: z.number().nullable(),
      unit: z.string(),
      definition_version: z.string(),
    })).min(1),
  }).strict(),
});

const findings = defineCollection({
  loader: json('findings'),
  schema: z.object({
    investigation: z.string(),
    items: z.array(z.object({
      id: z.string(),
      grade: z.enum(GRADES),
      text,
      support: z.record(z.string(), z.any()),
      limitations: text,
    })).min(1),
  }).strict(),
});

const charts = defineCollection({
  loader: json('charts'),
  schema: z.object({
    investigation: z.string(),
    slug,
    file: text,
    public_path: text,
    title: text,
    description: text,
    measures: z.array(slug).min(1),
    has_chronicle_marks: z.boolean().default(false),
    caption: text,
  }).strict(),
});

const datasets = defineCollection({
  loader: json('datasets'),
  schema: z.object({
    dataset_id: text,
    investigation: z.string(),
    publisher: text,
    name: text,
    url: z.string(),
    retrieved: isoDate,
    years: z.object({ from: z.number().int(), to: z.number().int() }),
    geography: text,
    format: text,
    sha256: z.string().regex(/^[0-9a-f]{64}$/),
    license: text,
    notes: z.string().default(''),
  }).strict(),
});

export const collections = {
  dimensions, places, populations, sources, developments, questions, corrections, records,
  investigations, measures, findings, charts, datasets,
};
